services:
  app:
    build:
      context: .
      target: dependencies # Use dependencies stage for dev to have devDeps
    command: pnpm run dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
